[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["src"]

[contracts]
main = ["src/contracts/NFTScavengerHunt.cairo"]

[profile.devnet.deploy]
gateway-url = "http://127.0.0.1:5050/"

